databases:
  - name: worldcup-2026-korea-bet-db
    plan: free
    databaseName: worldcup_bet
    user: worldcup_bet

services:
  - type: web
    name: worldcup-2026-korea-bet
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: worldcup-2026-korea-bet-db
          property: connectionString
    previews:
      generation: automatic
